<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <UseWpf>true</UseWpf>
    <RevitVersion>2027</RevitVersion>
    <DefineConstants>$(DefineConstants);REVIT2027;REVIT2023_OR_GREATER;REVIT2024_OR_GREATER;REVIT2025_OR_GREATER;REVIT2026_OR_GREATER;REVIT2027_OR_GREATER</DefineConstants>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <Configurations>Debug;Release;Local</Configurations>
  </PropertyGroup>

  <Import
    Project="..\Speckle.Connectors.RevitShared.WebView\Speckle.Connectors.RevitShared.WebView.projitems"
    Label="Shared"
  />
  <Import Project="..\Speckle.Connectors.RevitShared\Speckle.Connectors.RevitShared.projitems" Label="Shared" />

  <ItemGroup>
    <ProjectReference Include="..\..\..\Converters\Revit\Speckle.Converters.Revit2027\Speckle.Converters.Revit2027.csproj" />
    <ProjectReference Include="..\..\..\DUI3\Speckle.Connectors.DUI\Speckle.Connectors.DUI.csproj" />
    <ProjectReference Include="..\Speckle.Connectors.Revit.Common\Speckle.Connectors.Revit.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" IncludeAssets="compile" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Plugin\Speckle.Connectors.Revit2027.addin">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
