coverage:
  status:
    project:
      default:
        informational: true
        target: auto
        threshold: 1%
        base: auto
    patch:
      default:
        informational: true
github_checks:
  annotations: false