name: .NET Test

on:
  pull_request: {}
  push:
    branches: ["main"]

permissions: {} # We will use fine-grained permissions for each job, so we start with no permissions at all and then add them back as needed.

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true # other running workflows get cancelled on the same branch

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup .NET
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          dotnet-version: 10.0.2xx # Align with global.json (including roll forward rules)

      - name: Cache Nuget
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}

      - name: ⚒️ Run Test
        run: ./build.sh test-and-pack

      # Skipping codecov due to https://github.com/codecov/codecov-action/issues/1956 and fix being less than cooldown period

      # - name: Upload coverage reports to Codecov with GitHub Action
      #   uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354 # v6.0.1
      #   with:
      #     files: Converters/**/coverage.xml
      #     token: ${{ secrets.CODECOV_TOKEN }}

      # Disabling this code for now, since we no longer need to publish nugets from this repo
      # But keeping it around incase we ever need in the future.
      # Ideally, I'd also like to move the nuget token to be an environment secret, and to have tight package scopes
#      - name: Push to nuget.org
#        if: ${{ inputs.deployNugets }}
#        run: dotnet nuget push output/*.nupkg --source "https://api.nuget.org/v3/index.json" --api-key ${{ secrets.CONNECTORS_NUGET_TOKEN }}

  lint-github-actions:
    name: Lint GitHub Actions
    runs-on: ubuntu-latest
    permissions:
      contents: read # only needed for private or internal repos
      actions: read # only needed for private or internal repos
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Run zizmor 🌈
        uses: zizmorcore/zizmor-action@3dc1ecc9bcb9e94e9b2c709687979e1298497054 # v0.6.2
        with:
          advanced-security: false
